import type { Metadata } from "next";
import Cursor from "@/components/Cursor";
import { ThemeProvider } from "next-themes";
import Navbar from "@/components/Navbar";
import CircularScrollProgress from "@/components/CircularScrollProgress";
import Footer from "@/components/Footer";
import { Toaster } from "react-hot-toast";
import AnimatedPageWrapper from "@/components/AnimatedPageWrapper";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <CircularScrollProgress />
          <Cursor />
          <Navbar />
          <AnimatedPageWrapper>{children}</AnimatedPageWrapper>
          <Footer />
          <Toaster position="bottom-right" />
        </ThemeProvider>
      </body>
    </html>
  );
}
